[project]
name = "taqc-dataset-lib"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Denis Sokolinskiy", email = "eesokol22@gmail.com"},
]
dependencies = [
    "expression>=5.0.2",
    "more-itertools>=10.2.0",
    "pillow>=10.3.0",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true
